//created on: Dec 9, 2016
package com.line

//list any import classes here.



//declare any global variables here



import com.sample.Line;
rule "commenline remove"

    when
    		$AB : Line()
    		$CD : Line()
    		eval($AB != $CD)
    		eval($AB.sameItem($CD))
        //conditions
    then
    	retract($CD);
        //actions

end

rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end
