//created on: Dec 7, 2016
package com.parallelgrame

//list any import classes here.



//declare any global variables here


import com.sample.Angle;
import com.sample.Point;
import com.sample.Line;
import com.sample.Relation;
import com.sample.GeoType;
import com.sample.Triangle;
import com.sample.GeoRelation;
import com.sample.Quadrangle;
import com.engine.CheckingEngine;




rule "Theorem14"

    when
        //conditions
        //parallegrame
        $ABCD : Quadrangle(isAParalleologram==true)
        
    then
    //oposite line quals
        /*insert(new GeoRelation($ABCD.lines[0],$ABCD.lines[2],Relation.EQUALS));
		 insert(new GeoRelation($ABCD.lines[1],$ABCD.lines[3],Relation.EQUALS));
		 //oposite line parallel
		 insert(new GeoRelation($ABCD.lines[0],$ABCD.lines[2],Relation.PARALLEL_LINES));
		 insert(new GeoRelation($ABCD.lines[1],$ABCD.lines[3],Relation.PARALLEL_LINES));
		 //oposite angleequals
		 insert(new GeoRelation(new Angle($ABCD.lines[1],$ABCD.lines[0]),new Angle($ABCD.lines[3],$ABCD.lines[2]),Relation.EQUALS));
		 //oposite angleequals
		 insert(new GeoRelation(new Angle($ABCD.lines[2],$ABCD.lines[1]),new Angle($ABCD.lines[0],$ABCD.lines[3]),Relation.EQUALS));
		 insert(new GeoRelation(new Triangle($ABCD.lines[0],$ABCD.lines[1],$ABCD.lines[2]),new Triangle($ABCD.lines[0],$ABCD.lines[3],$ABCD.lines[2]),Relation.EQUALS))
		 insert(new GeoRelation(new Triangle($ABCD.lines[1],$ABCD.lines[2],$ABCD.lines[3]),new Triangle($ABCD.lines[1],$ABCD.lines[0],$ABCD.lines[3]),Relation.EQUALS))
		 
		 */
		
		 
		 System.out.println("Theorem14");
		 
end


